### ISSUE TITLE
null exception

### ISSUE THREAD

**Issue by lapkritinis** [titorenko/quick-csv-streamer#7]
I am parsing a file which among other lines has "empty" fields:

```
2.38.158.140/31,3172394,3175395,,0,0,80126,40.8563,14.2464,50
2.38.158.142/32,,3175395,,1,0,,,,
2.38.158.143/32,3172394,3175395,,0,0,80126,40.8563,14.2464,50
```
Last output from program is:

`City{network='2.38.158.140/31', geonameId=3172394, registeredCountryGeonameId=3175395, representedCountryGeonameId=, isAnonymousProxy='0', isSatelliteProvider='0', postalCode='80126', latitude=40.8563, longitude=14.2464, accuracyRadius=50}`

I have set it to sequential mode, so its easier to figure out where it fails.

```
Exception in thread "main" java.lang.NullPointerException
	at uk.elementarysoftware.quickcsv.parser.ByteArrayField.initFrom(ByteArrayField.java:90)
	at uk.elementarysoftware.quickcsv.parser.QuickCSVParser$LensingByteSliceSpliterator.parseFields(QuickCSVParser.java:227)
	at uk.elementarysoftware.quickcsv.parser.QuickCSVParser$LensingByteSliceSpliterator.tryAdvance(QuickCSVParser.java:217)
	at uk.elementarysoftware.quickcsv.parser.QuickCSVParser$SplittingSpliterator.tryAdvance(QuickCSVParser.java:80)
	at java.util.Spliterator.forEachRemaining(Spliterator.java:326)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at parser.Parser.main(Parser.java:18)
```

**Comment by lapkritinis** [comment]
I can tell it fails because of last item. If I change it - works.
2.38.158.142/32,,3175395,,1,0,,,,**50**

**Comment by lapkritinis** [comment]
```
        private void parseFields() {
            int[] skipSchedule = view.getFieldSkipSchedule();
            for (int i = 0; i < skipSchedule.length; i++) {
                skipFields(skipSchedule[i]);
                ByteArrayField field = super.getNextField();//TODO: init into template directly
                fieldTemplates[i].initFrom(field);
            }
        }

```

super.getNextField() returns null and than it fails on next step.

**Comment by titorenko** [comment]
Hi, can you please provide full example including how the parser is called, file content that you call it with and the mapping code. Thanks

**Comment by lapkritinis** [comment]
I made a sample based on your code:
https://github.com/Lapkritinis/quick-csv-streamer-cities-sample.git

**Comment by titorenko** [comment]
thanks, should be fixed now, will be in next release
